// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID   int64
	Name string
	Bio  pgtype.Text
}

type ChatRoom struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Message struct {
	ID        int64
	Content   string
	Type      pgtype.Text
	IsDelete  pgtype.Bool
	ParentID  pgtype.Int8
	CreatedAt pgtype.Timestamptz
	UserID    int64
	RoomID    int64
}

type MessageEmoteType struct {
	ID   int64
	Name string
}

type MessagesEmote struct {
	ID          int64
	MessageID   int64
	UserID      int64
	EmoteTypeID int64
}

type User struct {
	ID   int64
	Name string
}

type UsersAndChatRoom struct {
	ID     int64
	UserID int64
	RoomID int64
}
